### PR TITLE
Allow ContextWrapper to be cloned

### PR DESCRIPTION
**Pull request by richardwhiuk**
Benjamin,

This is a straight forward, backwards compatible, addition to ContextWrapper to allow it to be cloned.

As ContextWrapper simply contains a context, and a reference to the API, it should be possible to clone it if the Context itself is clone-able.

This makes it easier to write client APIs using code generated by Swagger because it means a client with a context can easily be cloned. A client without a context is already clone-able.

It'd be good if this could be merged into both 1.x and 2.x - but I don't currently see a 1.x stable branch?

### CODE REVIEW

**Comment by richardwhiuk** [comment]
Oh, I don't think either of the CI complaints are caused by this change. We don't seem to be pinning rustfmt, and the arguments to that have changed, and the crate doesn't appear to compile on nightly, which might be a rustc bug❗️.

**Comment by bjgill** [comment]
The nightly failure is due to you branching off an old version of master.

For rustfmt - do you want to pin the version? Otherwise, I can add a commit to do so.

**Comment by bjgill** [comment]
There is no 1.x stable branch - I'll backport this onto the last 1.0.x release and publish a new 1.0.x version.

How soon would you like this?

**Comment by richardwhiuk** [comment]
We don't have any particular timeframe here - for now we can patch swagger and point to this commit, but obviously it'd be good not to leave that tech-debt around.

Happy for you to pin rustfmt - the latest rustfmt needs `--check` instead of `writemode=diff`

**Comment by bjgill** [comment]
OK - I'm off on holiday shortly, but should be able to attend to this on Monday.

**Comment by bjgill** [comment]
Oops - I've just noticed this PR hanging around. I'll have a go at getting it merged.

**Comment by bjgill** [comment]
OK - v1.0.3 and v2.0.2 have now been published, both containing the fix in this PR

**Pull request merged**
