### PR TITLE
Add SwaggerContext trait used by swagger-codegen middleware

### PR DESCRIPTION
**Pull request by jngorman**
This change adds the SwaggerService trait to swagger-rs, this trait is used by swagger middlewares.

### CODE REVIEW

**Comment by jomala** [comment]
Looks fine as far as it goes.

I was expecting SwaggerService to include `C: Has<AuthData> + Has<Authorization> + Has<XSpanID>`, since that's what AddContext adds. Would this not simplify the code? Any reason not to?

And is there any advantage to defining `Has<AuthData> + Has<Authorization> + Has<XSpanID>` as `trait SwaggerBaseContext` or something like that?

**Comment by bjgill** [comment]
Thanks for the contribution. The code looks sensible.

Two things:
1. It looks as if `SwaggerService` is destined for use by middlewares. How will future middleware authors know how to use it?
2. (a minor point about testing that I'll make in the associated swagger-codegen PR)

**Comment by jngorman** [comment]
@bjgill Hi Ben, I've added some rust doc for SwaggerService, please can you have another look?

**Comment by bjgill** [comment]
Released as 1.0.1

**Pull request merged**
